### ISSUE TITLE
Some questions about dataset

### ISSUE THREAD

**Issue by sunset1995** [zouchuhang/LayoutNet#14]
Hello, 

Thank you for opensourcing this great work.
Recently I implemented LayoutNet using Pytorch [https://github.com/sunset1995/pytorch-layoutnet](https://github.com/sunset1995/pytorch-layoutnet) and found some questions about the ground truth data:
1. The numbers of line in `gt/pano*txt` is 1063 while the numbers of `gt/label_cor/**/*mat`is 1028. Can you please supplement the missing ground truth?
2. If I'm not wrong, labeled corner under `label_cor/**/*` should be scaled before visualization or evaluation. The scale for stanford2d3d and paonContext are `4.0` and `8.890625` respectively. Is that correct?

Thanks you and have a nice day :)

**Comment by zouchuhang** [comment]
@sunset1995 Thanks for your efforts ! Below are my responses:
1. There's no missing ground truth, please use the data matches the filenames in "gt/label_cor/**/*mat". For PanoContext dataset you can check the /data/ folder for correct mapping. For Stanford 2d-3d, we only labeled a subset with 4-walls room structure, which might cause the confusion of different number of labelings in the two folders when we collect the final version of the data.
2. The labeled corner are the 2D corner position matches the original image size in the dataset, if you visualize the original data in PanoContext and the Stanford 2d-3d, the corners shall match. If you use the images from the .t7 file, they are rotated and resized to 512*1024, which may cause the confusion.
Let me know if you have other questions.

**Comment by sunset1995** [comment]
Clear! Thanks for your reply.
