### ISSUE TITLE
Seems like gradient computation is not right, correct me if I am wrong

### ISSUE THREAD

**Issue by robotshanxi** [zouchuhang/LayoutNet#15]
https://github.com/zouchuhang/LayoutNet/blob/f0d05b884e0362c6f86b715740da7280ed53d1ff/matlab/sampleEijOpt.m#L44

line 44 and 45 and other lines after should be 
d_aob_x0 = (2*x0-1)*n_v_ao*n_v_bo/(sqrt(1-cos(b_aob)*cos(b_aob))+eps) + dot(v_ao, v_bo) * (x0*n_v_bo/n_v_ao + (x0-1)*n_v_ao/n_v_bo);
d_aob_x0 = -d_aob_x0 /n_v_ao/n_v_ao/n_v_bo/n_v_bo;

looks like only scale difference, but the optimization steps decrease.

**Comment by zouchuhang** [comment]
@robotshanxi term -1/(sqrt(1-cos(b_aob)cos(b_aob))+eps) is for the derivative of acos.
