### ISSUE TITLE
some poor images cannot make it

### ISSUE THREAD

**Issue by limchaos** [zouchuhang/LayoutNet#17]
Hi,really good work!
when I evaluated some images at optimization step,it's not work any more, I mean most images I used can make it,but except some of them ,for example, like this one below, can you help me:D

```
Undefined function or variable 'cor_fn_t'.
Error in samplingPanoBox (line 38)
            line_can(line_n+1:end,score_id(line_id)) =cor_fn_t(2*score_id(line_id),1);
```

<p align="center"><img width="50%" src="https://user-images.githubusercontent.com/33613957/44565187-7768ec80-a799-11e8-9517-3206dfd3d3c0.png" /></p>

<p align="center"><img width="50%" src="https://user-images.githubusercontent.com/33613957/44565194-7e8ffa80-a799-11e8-9d6c-e3aa2ba16118.png" /></p>

<p align="center"><img width="50%" src="https://user-images.githubusercontent.com/33613957/44565199-8485db80-a799-11e8-93f2-07f25b29a279.png" /></p>

**Comment by zouchuhang** [comment]
@limchaos Probably your number of "cor_id" send to the samplingPanoBox function is less than 8 (not all corners are detected). You need to check it first. If so, you can lower the hyper-parameter(value of MinPeakProminence) of function "findpeaks" in getIniCor.m to get full corners.

**Comment by limchaos** [comment]
I see,thanks for your help
