### ISSUE TITLE
3d layout construction

### ISSUE THREAD

**Issue by lyzband** [zouchuhang/LayoutNet#24]
hello @zouchuhang @alexcolburn 
I already checked the issue #3 but I still cannot fully understand the output.
since I do not have any background with 3d environment could you please explain some more details such as which tool to generate the mesh and wrap the pano, which variables to use, etc?

**Comment by zouchuhang** [comment]
@lyzband Please check https://github.com/zouchuhang/LayoutNet/issues/3#issuecomment-447431929
