### ISSUE TITLE
Some questions about edge map and cor_map

### ISSUE THREAD

**Issue by glacierwl** [zouchuhang/LayoutNet#31]
I want to test in my own dataset ,and i have got the label_cor,but i don't know how to get the edge_map and cor_map  from label_cor like you? Can you help me?

**Comment by glacierwl** [comment]
@zouchuhang

**Comment by zouchuhang** [comment]
@glacierwl Please check the sample code matlab/preprocessPano.m to get the edge_map and cor_map

**Comment by glacierwl** [comment]
Thank you for reply,I  solved this problem successfully  yesterday.
