### ISSUE TITLE
How to cover rotEdge(variable in getManhattanAndAlign.m ) to t7 ?

### ISSUE THREAD

**Issue by Ein027** [zouchuhang/LayoutNet#9]
I have successfully ran your code getManhattanAndAlign.m and test testNet_pano_full.lua on your demo, but i want to try it on my own pic. 
I see your code
`lne_ts = torch.load('./data/panoContext_line_test.t7')`
and 
`img_ts = torch.load('./data/panoContext_img_test.t7')`

it needs t7 file, but how can i cover  variable in matlab to t7 file?  it should be saved to image then saved to t7 file ? really thank you for your help.

**Comment by zouchuhang** [comment]
@Ein027 You can now refer to the sample code "preProcess_pano.lua" that converts gt data to .t7 file.

**Comment by zouchuhang** [comment]
@Ein027 Yes you need to save the images to png/jpeg format first then use the "preProcess_pano.lua" scripts to convert them to .t7.

**Comment by Ein027** [comment]
thank you so much, i will try it!

**Comment by Ein027** [comment]
Thanks ！
